services:
  latu:
    build: .
    env_file: ".env"
    container_name: taxonomy_trainer
    networks:
      - edge
    restart: unless-stopped
    expose:
      - 5000   # exposed to other containers on the network (not to host)

networks:
  edge:
    external: true


